### ISSUE TITLE
[1] - Mail de confirmation de création de compte pas reçu

### ISSUE THREAD

**Issue by IMiserez** [BMunier/pronostics-jdl#17]
Dejan Pepic / Login

Création de compte > pas reçu de mail de confirmation, j’ai vérifié avec l’équipe qui traite les SPAM, pas de mail dans les SPAM.

**Comment by BMunier** [comment]
C'est effectivement un point à configurer.

J'avais testé à l'époque en passant par une adresse gmail. 

Je vais voir pour remettre ça en place.
